name: CI workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
     - main

permissions:
  contents: read

jobs:
  unit_testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r API/requirements.txt

      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "API"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false

      - name: Run tests
        run: |
          python API/test_api.py